repos:
-  repo: local
   hooks:
   -  id: black
      name: black
      language: system
      entry: black --check --diff
      pass_filenames: true
      exclude: '^setup.py'
      types: [python]

